# Site settings
title: "Power BI Portfolio"
description: "Showcasing my Power BI projects and data analysis skills."
url: "https://yourusername.github.io/minimal"
baseurl: "" # the subpath of your site, e.g. /blog
author:
  name: "Your Name"
  email: "youremail@example.com"
  twitter_username: "yourtwitter"
  github_username: "yourusername"

# Build settings
theme: jekyll-theme-minimal
