# Site settings
title: "Power BI Portfolio"
description: "Showcasing my Power BI projects and data analysis skills."
url: "https://yourusername.github.io/minimal"
baseurl: "" # the subpath of your site, e.g. /blog
author:
  name: "Your Name"
  email: "youremail@example.com"
  twitter_username: "yourtwitter"
  github_username: "yourusername"

# Build settings
theme: jekyll-theme-minimal

---
layout: default
title: Home
---

# Welcome to My Power BI Portfolio

This is a showcase of my Power BI projects and data analysis skills.

## Featured Projects

- [Project One](projects/project-one.md)
- [Project Two](projects/project-two.md)
